main: com.advantageservers.demoserver.DemoServer
name: Demo
version: 1.0
description: Light plugin to provide functionality on our demo server
author: Dylan Hansch
website: https://advantageservers.com
commands:
    gamemode:
        description: Set player gamemode
        usage: /<command> <mode> [player]
        aliases: [gm]
    setspawn:
        description: Set server spawn
        usage: /<command>
    spawn:
        description: Teleport to server spawn
        usage: /<command> [player]
permissions:
    demo.*:
        description: Server Admin
        default: op
        children:
            demo.gamemode.others: true
            demo.setspawn: true
            demo.spawn.others: true